#!/usr/bin/env python3
"""
Setup wizard for Sage Feature Team in any project.

Generates:
  - <project_root>/sage-config.yaml         minimal team config
  - <project_root>/.sage/                   per-agent instruction files (skeletons)

The skeletons have an empty `instructions:` list. Edit them to point the agents
at the project's own markdown docs (test guides, code conventions, etc.).

Usage:
    python setup_project.py
"""

import os
import re
import sys
from pathlib import Path


AGENT_SLUGS = ["product-owner", "test-creator", "developer", "tester"]


def slugify(name):
    return re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-")


def prompt(question, default=None, required=True):
    suffix = f" [{default}]" if default is not None else ""
    while True:
        ans = input(f"{question}{suffix}: ").strip()
        if not ans and default is not None:
            return default
        if ans:
            return ans
        if not required:
            return ""
        print("This field is required.")


def prompt_path(question, default=None):
    while True:
        p = prompt(question, default=default)
        path = Path(p).expanduser()
        if path.exists() and path.is_dir():
            return str(path.resolve())
        print(f"Not a directory: {p}")


def prompt_yes_no(question, default=True):
    suffix = "Y/n" if default else "y/N"
    while True:
        ans = input(f"{question} [{suffix}]: ").strip().lower()
        if not ans:
            return default
        if ans in ("y", "yes"):
            return True
        if ans in ("n", "no"):
            return False


def render_sage_config(name, abs_root):
    slug = slugify(name)
    return f"""# Sage Feature Team config for {name}
# Generated by setup_project.py

project:
  name: "{name}"
  root_dir: "."
  absolute_root_dir: "{abs_root}"

team:
  name: "{slug}-feature-team"
  dev_test_team_name: "{slug}-dev-test-team"
  agents:
    full:
      - name: "ProductOwner"
        file: "agents/product-owner.md"
      - name: "TestCreator"
        file: "agents/test-creator.md"
      - name: "Developer"
        file: "agents/developer.md"
      - name: "Tester"
        file: "agents/tester.md"
    dev_test_only:
      - name: "Developer"
        file: "agents/developer.md"
      - name: "Tester"
        file: "agents/tester.md"

paths:
  output_dir: "_output"
  # sage_dir defaults to <absolute_root_dir>/.sage if not set
  # sage_dir: ".sage"

limits:
  max_cycles: 5
"""


def render_agent_skeleton(slug):
    title = slug.replace("-", " ").title()
    return f"""# {title} instructions for this project
#
# Each line below is a project-specific instruction. The agent reads these
# at startup and uses Read tool to fetch any referenced files at runtime.
#
# Examples of good instructions:
#   - "When running tests, follow docs/run_tests.md exactly."
#   - "Read docs/coding_conventions.md before writing any code."
#   - "Test files go in tests/<area>/test_<feature>.py — never anywhere else."
#   - "Specs use the template in docs/spec_template.md."
#
# Keep instructions short and concrete. Point at files for detail.

instructions: []
"""


def main():
    print("=" * 70)
    print("Sage Feature Team — Project Setup")
    print("=" * 70)

    name = prompt("Project name (e.g., 'Breadcrumbs')")
    abs_root = prompt_path("Project root directory", default=os.getcwd())

    project_root = Path(abs_root)
    sage_dir = project_root / ".sage"
    config_path = project_root / "sage-config.yaml"

    print()
    print(f"Will create:")
    print(f"  {config_path}")
    print(f"  {sage_dir}/  (with 4 skeleton agent configs)")
    print()
    if not prompt_yes_no("Proceed?", default=True):
        print("Cancelled.")
        return 1

    # Write sage-config.yaml
    if config_path.exists():
        if not prompt_yes_no(f"{config_path} exists. Overwrite?", default=False):
            print("Skipping sage-config.yaml.")
        else:
            config_path.write_text(render_sage_config(name, abs_root), encoding="utf-8")
            print(f"  wrote {config_path}")
    else:
        config_path.write_text(render_sage_config(name, abs_root), encoding="utf-8")
        print(f"  wrote {config_path}")

    # Create .sage/ skeletons
    sage_dir.mkdir(parents=True, exist_ok=True)
    for slug in AGENT_SLUGS:
        f = sage_dir / f"sage-{slug}-config.yaml"
        if f.exists():
            print(f"  skipped {f} (already exists)")
            continue
        f.write_text(render_agent_skeleton(slug), encoding="utf-8")
        print(f"  wrote {f}")

    print()
    print("Done. Next steps:")
    print(f"  1. Edit each .sage/sage-*-config.yaml — fill in `instructions:` with")
    print(f"     project-specific guidance (point at your own docs).")
    print(f"  2. Run: /sage-feature-team \"Your feature\"")
    return 0


if __name__ == "__main__":
    sys.exit(main())
