"""STORY-3 end-to-end + idempotency tests for ``python -m ssg build``.

Seam under test: the whole pipeline as a user runs it -- a real ``content/``
tree on disk, an actual ``python -m ssg build`` subprocess, and byte-level
assertions on the produced ``dist/``.

These tests own the two PRD guarantees that only make sense at the full-build
boundary:

  - AC18 (idempotency): two consecutive builds on unchanged content produce
    byte-identical ``dist/`` output (every file's bytes match across runs).
  - AC19 (snapshot): building against ``tests/fixtures/sample_site/content/``
    produces a ``dist/`` that matches ``tests/fixtures/expected_dist/``
    file-for-file and byte-for-byte.

The snapshot fixture is the canonical description of the build's output -- the
per-page HTML was generated by the real (DONE) parser+renderer, and
``expected_dist/index.html`` fixes the index template the Developer must
produce: posts in an ``<ul>`` sorted by date descending (date-less last,
alphabetical by title), each ``<li>`` linking the title to ``<basename>.html``
with a ``<span class="date">`` only when the post has a date. If the Developer
chooses different index markup, update the fixture deliberately and review the
diff (per docs/testing.md), but the structural facts above are required by the
PRD (AC13).

All fixtures are committed as LF-newline files; the build is expected to write
LF as well, so byte comparison is platform-stable.

All tests are named ``test_story_3_*`` so the Tester can filter with
``pytest -k "story_3"``.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = PROJECT_ROOT / "src"
FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
SAMPLE_CONTENT = FIXTURES_DIR / "sample_site" / "content"
EXPECTED_DIST = FIXTURES_DIR / "expected_dist"


def _run_build(cwd: Path) -> subprocess.CompletedProcess:
    env = {
        **dict(os.environ),
        "PYTHONPATH": str(SRC_DIR),
        "PYTHONIOENCODING": "utf-8",
        "PYTHONUTF8": "1",
    }
    return subprocess.run(
        [sys.executable, "-m", "ssg", "build"],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        env=env,
    )


def _copy_sample_content_into(workdir: Path) -> None:
    """Copy the sample_site content tree into ``workdir/content/``."""
    import shutil

    dst = workdir / "content"
    shutil.copytree(SAMPLE_CONTENT, dst)


def _dist_snapshot(dist: Path) -> dict[str, bytes]:
    """Map relative path -> raw bytes for every file under ``dist/``."""
    return {
        str(p.relative_to(dist)).replace(os.sep, "/"): p.read_bytes()
        for p in sorted(dist.rglob("*"))
        if p.is_file()
    }


# --- AC18: two consecutive builds are byte-identical -------------------------

def test_story_3_build_is_idempotent_byte_identical(tmp_path):
    _copy_sample_content_into(tmp_path)
    dist = tmp_path / "dist"

    first = _run_build(tmp_path)
    assert first.returncode == 0, first.stderr
    snapshot_one = _dist_snapshot(dist)

    second = _run_build(tmp_path)
    assert second.returncode == 0, second.stderr
    snapshot_two = _dist_snapshot(dist)

    # Same set of files and identical bytes for each across the two runs.
    assert snapshot_one.keys() == snapshot_two.keys()
    for name in snapshot_one:
        assert snapshot_one[name] == snapshot_two[name], f"{name} differs across builds"


# --- AC19: build output matches the expected_dist snapshot byte-for-byte -----

def test_story_3_e2e_matches_expected_dist_snapshot(tmp_path):
    _copy_sample_content_into(tmp_path)
    dist = tmp_path / "dist"

    result = _run_build(tmp_path)
    assert result.returncode == 0, result.stderr

    produced = _dist_snapshot(dist)
    expected = _dist_snapshot(EXPECTED_DIST)

    # Same file set.
    assert produced.keys() == expected.keys(), (
        f"file set differs: produced={sorted(produced)} expected={sorted(expected)}"
    )
    # Byte-for-byte identical per file.
    for name in expected:
        assert produced[name] == expected[name], (
            f"{name} bytes differ from expected_dist snapshot"
        )


def test_story_3_e2e_summary_counts_sample_pages(tmp_path):
    _copy_sample_content_into(tmp_path)

    result = _run_build(tmp_path)
    assert result.returncode == 0, result.stderr

    lines = [ln for ln in result.stdout.splitlines() if ln.strip()]
    assert len(lines) == 1, result.stdout
    # sample_site/content has 4 source .md files; index is not counted.
    import re

    match = re.match(r"^built (\d+) pages in (\d+)ms$", lines[0])
    assert match is not None, repr(lines[0])
    assert match.group(1) == "4"
